project_id = "rhubaybwftyypfbiuoyc"

[functions.admin-users]
verify_jwt = true

[functions.send-task-email]
verify_jwt = false

[functions.send-project-email]
verify_jwt = false

[functions.send-project-approval-email]
verify_jwt = false

[functions.send-planning-notification]
verify_jwt = false

[functions.send-project-rejection-email]
verify_jwt = false

[functions.send-project-correction-email]
verify_jwt = false
